name: Docker Image Run Tests

on:
  workflow_dispatch:
    inputs:
        MONGO_URL:
          description: 'Connection URI to mongodb'     
          required: true
        VERIFY_TOKEN_URL:
          description: 'TeamService endpoint to verify tokens'
          required: true
        AUTH_TOKEN:
          description: 'Auth token sent to TeamService '
          required: true
        SENDGRID_API_KEY:
          description: 'SendGrid API Key'
          required: true
        SENDGRID_SENDER_EMAIL:
          description: 'SendGrid email sender (the api key owner must haved added it as verified mail)'
          required: true

env:
  SECRET_KEY: gjklbhb1iu2g34iup1g23p4iu12h3jkh123uii
  DEBUG: 1
  MONGO_URL: ${{ inputs.MONGO_URL }}
  PORT: 8080
  VERIFY_TOKEN_URL: ${{ inputs.VERIFY_TOKEN_URL }}
  SENDGRID_API_KEY: ${{ inputs.SENDGRID_API_KEY }}
  SENDGRID_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_SENDER_EMAIL: ${{ inputs.SENDGRID_SENDER_EMAIL }}
  PLAYER_SERVICE_URL: http://localhost:8080
  AUTH_TOKEN: ${{ inputs.AUTH_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pylint and requests
      run: pip install -r player_service/requirements.txt;
    - name: Start player service
      run: cd player_service; gunicorn --bind 0.0.0.0:8080 wsgi:app --daemon
    - name: Test
      run: cd player_service; pytest
