name: Docker Image Run Tests

on:
  workflow_dispatch:

env:
  SECRET_KEY: gjklbhb1iu2g34iup1g23p4iu12h3jkh123uii
  DEBUG: 1
  MONGO_URL: mongodb+srv://johnsiel19:John1234@cluster0.nievztx.mongodb.net/footmatch
  PORT: 8080
  VERIFY_TOKEN_URL: https://team-service-danaremar.cloud.okteto.net/api/v1/validate-token # seria conveniente usar el se desarrollo o desplegar el servicio nosotros mismos ()
  SENDGRID_API_KEY: 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
  SENDGRID_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_SENDER_EMAIL: joscrulor@alum.us.es
  PLAYER_SERVICE_URL: localhost:8080 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pylint and requests
      run: pip install -r player_service/requirements.txt;
    - name: Start player service
      run: cd player_service; gunicorn --bind 0.0.0.0:8080 wsgi:app --daemon
    - name: Test
      run: cd player_service; pytest
